title:              Educ Chien Essonne
email:              educchien66@gmail.com
description:        Créer l'harmonie entre maître et chien
author:             Franck Guéville
baseurl:            ""
url:                "https://educchienessonne.github.io/"

# Social Profiles
twitter_username:   
github_username:    
facebook_username:  EducChien Essonne
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap 
  
  ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
